### ISSUE TITLE
User Journey

### ISSUE THREAD

**Issue by mcmullenrich** [mcmullenrich/PDICapstone1#2]
My ideal user journey for my budgeting app is as follows:

The user logs in and is presented with a menu: 
1. Create budget 
2. Create spend category 
3. Enter budget amount 
4. Enter income/expense 
5. Create budget vs actual report

Create budget would require a budget name and a date range (start, end). 

Create spend category would require the budget(s) it applies to and the category name. 

Enter budget amount would require the budget name, spend category, and budget amount. 

Enter income/expense would require the budget category, date, and amount. 

Creating the budget vs actual report would summarize the amounts for the selected date range and comparing the totals. It should also show the difference in dollars and percentage for each category and the grand total.

**Comment by JnyJny** [comment]
One thing I really like the user journey to include is feelings since stronger feelings are often indicative of the features that are most important to you. That gives a stronger signal when we're trying to prioritize all the features identified by the journey.  Something like.

> I really like making my monthly budget, it's so easy to start and keep up with! At the beginning of the month I set the target I want to stay under for my monthly spending.  Then whenever I make an expenditure, updating my spending is so easy and fun that I don't want to skip it.  I go to a teminal window and type in "budget --update 10.00 --category gas" and it prints out a cool summary of my budget progress so far this month with funny emojis to encourage me. I can always check my budget with "budget --status" and get that cool summary before I spend just to make sure I won't blow my budget.  At the end of the month I can close out the budget knowing that I've come in under my target and see where all my spending was by category and start the next month with a good idea of how I'm spending my money. It really gives me a great feeling of control over my life.

If you're game, re-write your user journey in a couple paragraphs that describe how you would want the user to feel (the user is you) while they are using the tool.

**Comment by mcmullenrich** [comment]
A good budget app is like a gps system, helping me figure out which way to turn so I can reach my destination. For me, that is peace of mind. I prefer to make a high level budget for the coming year in December. This gives me a sense of what I'm working towards. Then I like to break it up monthly for any seasonal issues (e.g., birthdays, holidays, other large expenditures, etc.). Once my system is up and running, I'd love to be able to login and get an overview of where I stand at any given moment. It should also be really easy to update my expenditures as I go. For one-off's, I could enter it via the command line. But if I'm behind, I'd love to be able to feed it a csv file so I could batch upload an entire month in one shot. Each month, quarter, year-end, I should get a report showing how I did compared to budget.
