### ISSUE TITLE
Create A Single File Script in the utility.py file

### ISSUE THREAD

**Issue by JnyJny** [mcmullenrich/PDICapstone1#3]
Create your own program structure in the utility.py file since it's already there and it's empty.  I've committed the doit.py script for you to use as an example.

If you are so inclined you could read the [article][1] I wrote about command-line interfaces (CLIs) which is an unabashed love letter. It explains the history and terminology of the UNIX command line which is the model that Python emulates and uses "under the covers". If it's just too much, you can skip to the end where I talk specifically about the various ways of implementing a CLI with Python and it won't hurt my feelings.

[1]: https://github.com/JnyJny/articles/blob/master/python/python_clis.md

**Comment by mcmullenrich** [comment]
I've updated the utility.py file to include the argument parsing functionality we spoke about.

**Comment by JnyJny** [comment]
Excellent work!  I really like that you used some different command line arguments and options.

**Comment by JnyJny** [comment]
With respect to issues, the opener and the assignee generally agree that the problem is "solved" before the issue is closed. I'm really happy with the script you wrote; I see a clear understanding of the task and how to accomplish it and I see some creativity that signals you might have had fun with this task :) Nicely done and _now_ we'll close the issue!
